services:
  - type: web
    name: beacon-cinema-calendar-sync
    env: node
    buildCommand: 'mkdir -p /opt/render/.cache/puppeteer && npm install && PUPPETEER_CACHE_DIR=/opt/render/.cache/puppeteer npx puppeteer browsers install chrome'
    startCommand: 'npm start'
    envVars:
      - key: CALENDAR_ID
        sync: false
      - key: TIME_ZONE
        sync: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
        sync: false
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
        sync: false
    autoDeploy: true
    plan: free
    rootDir: .
    # Optionally, add disk for persistent logs or files
    # disks:
    #   - name: data
    #     mountPath: /data
