services:
  - type: web
    name: beacon-cinema-calendar-sync
    env: node
    buildCommand: 'npm install && npx puppeteer browsers install chrome --path /opt/render/.cache/puppeteer'
    startCommand: 'npm start'
    envVars:
      - key: CALENDAR_ID
        sync: false
      - key: TIME_ZONE
        sync: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
        sync: false
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
        sync: false
      - key: MAX_LOG_SIZE_MB
        value: 5
        sync: false
      - key: MAX_LOG_FILES
        value: 3
        sync: false
      - key: LOG_RETENTION_DAYS
        value: 14
        sync: false
    autoDeploy: true
    plan: free
    rootDir: .
    # Optionally, add disk for persistent logs or files
    # disks:
    #   - name: data
    #     mountPath: /data
